In [1]:
import numpy as np
import pandas as pd

## PageRank Problem

In [2]:
links = np.array(pd.read_csv('LinkData.csv')) # put your file location here
# i personally hate pandas.  loc, iloc, at, slices ... it's all hard to remember...
# R does dataframes so much better
# so i translated to an np array, they're easier to deal with..

In [8]:
npages = links.shape[0] # how many pages
P = np.zeros((npages,npages)) # initialize the P matrix with all zeros, then come back later to fix
P

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
for row in range(npages):
    links_this_page = np.sum(links[row,:]) # how many trues on this row
    P[row,links[row,:]] = 1.0/links_this_page 
    # if True, then there is a link from page row to that page so set set P to be 1/number of trues at each true

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.14285714, 0.        , 0.        , ..., 0.14285714, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

Logical indexing is also called masking

In [21]:
start_page = 16
click_page = 17
P[start_page,click_page]

0.025

In [22]:
col_to_sum = 92
np.sum(P[:,col_to_sum])

0.24447055137844612

In [ ]:
v = np.ones((1,npages))/npages # equally likely to start on each page
v

In [ ]:
v2 = v @ P # do the mulitplication
v2

In [ ]:
np.sum(v2)

In [ ]:
np.sum(v2[0,0:25])

In [ ]:
np.sum(v2[0,75:])

array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
        0.01]])

In [26]:
nloop = 10
vold = np.ones((1,npages))/npages
for i in range(nloop):
    vnew = vold @ P
    vold = vnew.copy() # another thing that annoys me about python...all lists/vectors are pointers...i never know when I need to use copy

vnew = vold @ P
np.max(np.abs(vnew-vold)) # this was enough iterations of the loop

3.811623702429379e-09

In [ ]:
vnew

In [ ]:
which_page = 60
vnew[0,which_page]

In [ ]:
np.argmax(vnew)

In [ ]:
np.argmin(vnew)

In [ ]:
np.argsort(vnew)[0][::-1]