In [12]:
import numpy as np
import pandas as pd
import gurobipy as gp

# Question 2

In [13]:
A = np.array([[0,1,0,2],[2,-3,1,-0.5],[-5,6,0,1],[0,-1,1,0]])
B = np.array([190,-34,64,2])
x = np.linalg.solve(A,B)
x

array([ 4.00000000e+00, -2.00000000e+00,  2.98427949e-14,  9.60000000e+01])

# Question 4

In [14]:
 obj = np.array([125,-15,75,75,-15,100]) # objective vector profit = revenue - cost
A = np.zeros((6,6)) # initialize constraint matrix
A[0,:] = [300,15,100,300,15,100] # cost
A[1,:] = [-4,1,0,0,0,0] # IPA 4 times more wheat
A[2,:] = [0,0,0,-1,0,1] 
A[3,:] = [0,0,0,-5,1,0] # Ockto 5 times more wheat
A[4,:] = [-300,500,0,0,0,0] #alcohol%
A[5,:] = [0,0,0,-300,500,0] #alcohol%

b = np.array([4100,0,0,0,7500,5250]) # limits 
sense = np.array(['<','>','>','>','>','>']) # all constraints are less than or equal constraints
A

array([[ 300.,   15.,  100.,  300.,   15.,  100.],
       [  -4.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,   -1.,    0.,    1.],
       [   0.,    0.,    0.,   -5.,    1.,    0.],
       [-300.,  500.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0., -300.,  500.,    0.]])

In [15]:
ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(6,lb=np.array([4,10,0,2,10,3])) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model...we'll talk about the None and the 0

ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!
ojModel.Params.TimeLimit = 3600
ojModel.optimize() # solve the LP
ojModel.objVal # optimal revenue level


2077.0

In [16]:
ojModX.x

array([ 4.   , 17.4  ,  0.   ,  2.   , 11.7  , 18.635])

In [17]:
[con.SARHSLow for con in ojModCon]

[2536.5, -inf, -inf, -inf, 6799.999999999999, 4400.0]