<h2>Problem 1</h2>

In [1]:
import numpy as np

A = np.zeros((4,4))
A[0,:] = [1,1,1,1]
A[1,:] = [0.01,-0.05,-0.05,0.05]
A[2,:] = [0.45,-0.55,0,0]
A[3,:] = [-0.25,0.75,-0.25,-0.25]

b = np.array([250,0,0,0])
xyz = np.linalg.solve(A,b)
xyz

array([76.38888889, 62.5       , 31.94444444, 79.16666667])

$31.94M is lent in home improvement loans

<h2>Problem 2 part 1</h2>

In [6]:
X = np.zeros((10,5))
X[0,:] = [1,-1,0,0,0]
X[1,:] = [1,0,-1,0,0]
X[2,:] = [1,0,0,-1,0]
X[3,:] = [1,0,0,0,-1]
X[4,:] = [0,1,-1,0,0]
X[5,:] = [0,1,0,-1,0]
X[6,:] = [0,1,0,0,-1]
X[7,:] = [0,0,1,-1,0]
X[8,:] = [0,0,1,0,-1]
X[9,:] = [0,0,0,1,-1]
X

array([[ 1., -1.,  0.,  0.,  0.],
       [ 1.,  0., -1.,  0.,  0.],
       [ 1.,  0.,  0., -1.,  0.],
       [ 1.,  0.,  0.,  0., -1.],
       [ 0.,  1., -1.,  0.,  0.],
       [ 0.,  1.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  1.,  0., -1.],
       [ 0.,  0.,  0.,  1., -1.]])

In [15]:
Y = np.zeros((10,1))
Y[0,:] = [-45]
Y[1,:] = [-3]
Y[2,:] = [-31]
Y[3,:] = [-45]
Y[4,:] = [18]
Y[5,:] = [8]
Y[6,:] = [20]
Y[7,:] = [2]
Y[8,:] = [-27]
Y[9,:] = [-38]
Y

array([[-45.],
       [ -3.],
       [-31.],
       [-45.],
       [ 18.],
       [  8.],
       [ 20.],
       [  2.],
       [-27.],
       [-38.]])

<h2>Part 2</h2>

In [18]:
XT = np.transpose(X)
M = XT @ X
M

array([[ 4., -1., -1., -1., -1.],
       [-1.,  4., -1., -1., -1.],
       [-1., -1.,  4., -1., -1.],
       [-1., -1., -1.,  4., -1.],
       [-1., -1., -1., -1.,  4.]])

In [20]:
P = XT @ Y
P

array([[-124.],
       [  91.],
       [ -40.],
       [ -17.],
       [  90.]])

<h2> Part 3</h2>

In [24]:
MC = M
MC[4,:] = [1,1,1,1,1]

PC=P
PC[4,:] = [0]

In [26]:
MC

array([[ 4., -1., -1., -1., -1.],
       [-1.,  4., -1., -1., -1.],
       [-1., -1.,  4., -1., -1.],
       [-1., -1., -1.,  4., -1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [28]:
PC

array([[-124.],
       [  91.],
       [ -40.],
       [ -17.],
       [   0.]])

In [29]:
soln = np.linalg.solve(MC,PC)
soln

array([[-24.8],
       [ 18.2],
       [ -8. ],
       [ -3.4],
       [ 18. ]])

<h2>Problem 3</h2>

In [46]:

rows=20
columns=20
A = np.zeros((20,20))
for i in range(rows):
    for j in range(columns):
        if i>j:
            A[i][j]=(j+1)/(i+1)
        else:
            A[i][j]=(i+1)/(j+1)

B=A.transpose()

def areSame(A,B):

    for i in range(rows):
        for j in range(columns):
            if (A[i][j] != B[i][j]):
                return 0
    return 1

areSame(A,B)


1

A is symmetric

<H2>Problem 4</H2>

In [47]:
C = np.linalg.inv(A)

In [48]:
d=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[10],[9],[8],[7],[6],[5],[4],[3],[2],[1]])

In [49]:
E = C @ d

In [51]:
sol4 = np.linalg.solve(A,E)
sol4[9]

array([20.06423927])

In [52]:
A

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.5       , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
        0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
        0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ],
       [0.33333333, 0.66666667, 1.        , 0.75      , 0.6       ,
        0.5       , 0.42857143, 0.375     , 0.33333333, 0.3       ,
        0.27272727, 0.25      , 0.23076923, 0.21428571, 0.2       ,
        0.1875    , 0.17647059, 0.16666667, 0.15789474, 0.15      ],
       [0.25      , 0.5       , 0.75      , 1.        , 0.8       ,
        0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ,
        0.36363636, 0.33333333, 0.30769231, 0